### ISSUE TITLE
Problem downloading zip file

### ISSUE THREAD

**Issue by devolution2409** [alex-spataru/QSimpleUpdater#11]
Hi, basically i wanted to update the whole application with a github release link.
My json is configured properly, with the link being:
https://github.com/devolution2409/Lidl-Soundboard/releases/download/1.1.2/LIDL_Soundboard.zip

If i try to download the zip through the QSimpleUpdater, it will download a 1KB corrupted zip.
However, if i set `QSimpleUpdater::getInstance()->setDownloaderEnabled(url,false);`

The link will be opened in the default browser, and it will correctly download the 9MB file.

Am i doing something wrong?
Thanks in advance

**Comment by alex-spataru** [comment]
Hello!

Sorry for the (very) late reply, I did not catch the notification email about this issue.

It is possible that the QNetworkReply class does not handle redirections as it should (check [this](https://github.com/alex-spataru/QSimpleUpdater/blob/master/src/Downloader.cpp#L140) line for more info).  For the moment, you might want to play with the user-agent string ([more info](https://github.com/alex-spataru/QSimpleUpdater/blob/master/include/QSimpleUpdater.h#L102), it *may* affect how the download is delivered to your computer.

I will test the downloader with GitHub releases later this weekend, maybe I can come up with a fix.
