### ISSUE TITLE
Unintentionally left semicolon

### ISSUE THREAD

**Issue by dschulz** [alex-spataru/QSimpleUpdater#25]
It seems like there's a dangling semicolon in this line:

`uint difference = QDateTime::currentDateTime().toSecsSinceEpoch(); - m_startTime;
`
This might cause a wrong difference time calculation.

https://github.com/alex-spataru/QSimpleUpdater/blob/3e2b4bc69758de982bddcb3fe471e2e5050025bd/src/Downloader.cpp#L378

**Comment by alex-spataru** [comment]
Just fixed it! Thanks!
