### ISSUE TITLE
when i press check for update on my app i get this error  qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

### ISSUE THREAD

**Issue by Kaysharp42** [alex-spataru/QSimpleUpdater#27]
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

**Comment by alex-spataru** [comment]
Hi! You need to bundle OpenSSL libraries alongside your application binary in order for SSL-related functions to work. Here are some links that may help you:

- [https://stackoverflow.com/questions/14681012/how-to-include-openssl-in-a-qt-project](https://stackoverflow.com/questions/14681012/how-to-include-openssl-in-a-qt-project)

For Windows, I have a [template app](https://github.com/alex-spataru/QtApp-Template) that bundles OpenSSL binaries while generating the NSIS installer, you might want to take a look at the repo.
