### ISSUE TITLE
Consider an OSI-approved license

### ISSUE THREAD

**Issue by principis** [alex-spataru/QSimpleUpdater#28]
The BDAD license is quite hilarious. Sadly it's not OSI-approved, which makes it difficult to use it in other projects or package software using this library in Linux distributions.
Would you consider changing the license to an [OSI-approved](https://opensource.org/licenses/category) license like MIT or BSD? 

Thanks!

**Comment by alex-spataru** [comment]
Hi! I wrote this project during high school, so I didn't really care about the license 😆. I'll update the license to MIT later today.

**Comment by principis** [comment]
@alex-spataru Thank you! This will at least solve the licensing issue for [github.com/mooltipass/moolticute](moolticute) :smiley:

**Comment by alex-spataru** [comment]
@principis As of the latest commit, the project is now released under the terms & conditions of the MIT license. Thanks for the issue report!
