### ISSUE TITLE
Updater doesn't properly follow redirects

### ISSUE THREAD

**Issue by dail8859** [alex-spataru/QSimpleUpdater#29]
Windows 10
Qt 5.15.2
MSVC 2019 64-bit

I'm attempting to use this project and download an exe from a Github release (specifically https://github.com/dail8859/NotepadNext/releases/download/v0.4.1/NotepadNext-v0.4.1-Installer.exe). However when using this project as is, it downloads a 0 byte file, and also seems kick off two different downloads (two prompts for `Click "OK" to begin installing the update`).

As issues in this repo seem to indicate, this is related to network redirects. The example project in this repo does not have the issue since it directly accesses a URL with no redirect (i.e. https://raw.githubusercontent.com/alex-spataru/QSimpleUpdater/master/tutorial/download/YesItWorks.jpg)

Related issues: #13, #11
Probably related: #26

I've made some minor changes that seems to fix the immediate issue. I can create a PR if needed but I'll at least describe the changes if you want to make them directly.

Right after `request` is created:

https://github.com/alex-spataru/QSimpleUpdater/blob/76a27c072357b857f4f5584006a4a55869aa1f42/src/Downloader.cpp#L112

The policy needs set to follow redirects.
```cpp
request.setAttribute(QNetworkRequest::RedirectPolicyAttribute, QNetworkRequest::NoLessSafeRedirectPolicy);
```

Also, to prevent the multiple downloads, this line needs removed:

https://github.com/alex-spataru/QSimpleUpdater/blob/76a27c072357b857f4f5584006a4a55869aa1f42/src/Downloader.cpp#L131

---
No idea if this works on Qt6+

**Comment by alex-spataru** [comment]
Hi, thanks a lot for the report and the solution! If possible, please make a PR so that your solution appears to all users of this library :)
