### ISSUE TITLE
Regular expression matching download filename failed

### ISSUE THREAD

**Issue by L-Super** [alex-spataru/QSimpleUpdater#38]
https://github.com/alex-spataru/QSimpleUpdater/blob/2a06879a42f27db43fc8edc2a2ccd0aff8318c30/src/Downloader.cpp#L352-L353

Content disposition header:
```
Content-Disposition | attachment; filename=xxx_1.0.16_uos_amd64.deb
```
The result is null.

**Comment by L-Super** [comment]
```cpp
QRegularExpression regex("filename=(\\S+)");
```
It's pass.

**Comment by alex-spataru** [comment]
Hi! Thanks for pointing out this issue and providing a fix! Do you want to open a pull request (so that you appear as a contributor to this project), or do you prefer for me to add the fix? Greetings from Mexico! 🇲🇽

**Comment by L-Super** [comment]
> Greetings from Mexico! 

I would be very happy to provide a PR

**Comment by alex-spataru** [comment]
Thanks! I just merged your PR. Closing this issue...
