### ISSUE TITLE
Custom JSON update

### ISSUE THREAD

**Issue by alejandro-pnz** [alex-spataru/QSimpleUpdater#4]
Hi! This project is pretty good, but I've got a one question. In case of custom JSON, there is no other way to do it, exclude to fork & re-write **Updater::onReply** function. Maybe the library contains other ways to do it?

**Comment by alex-spataru** [comment]
Hi! For the moment, the QSimpleUpdater does not provide a way to read custom JSON files, however, it is really easy to implement the code that allows the application to handle custom JSONs (or any kind of replies). 

I will work on this issue later today and post updates through this thread.

**Comment by alex-spataru** [comment]
I have added a [function to the QSimpleUpdater](https://github.com/alex-spataru/QSimpleUpdater/blob/master/src/QSimpleUpdater.cpp#L320) which allows your application to read and interpret the downloaded appcast file. Let me know if it works for you!
