### ISSUE TITLE
If the network is interrupted, the download status will never be updated.

### ISSUE THREAD

**Issue by L-Super** [alex-spataru/QSimpleUpdater#40]
During the process of downloading, if the network is interrupted, it will remain in the downloading state without timing out or reporting errors. It may be possible to set an appropriate timeout to timely update the download status.

https://doc.qt.io/qt-5/qnetworkrequest.html#setTransferTimeout

```c++
void QNetworkRequest::setTransferTimeout(int timeout = DefaultTransferTimeoutConstant)
```

·

**Comment by alex-spataru** [comment]
Hi again @L-Super! Thanks for pointing out this issue and (again) providing a possible fix. As last time, would you like to open a PR (and set a timeout constant that works for your usage scenario), or shall I add the fix?

**Comment by L-Super** [comment]
> Hi again @L-Super! Thanks for pointing out this issue and (again) providing a possible fix. As last time, would you like to open a PR (and set a timeout constant that works for your usage scenario), or shall I add the fix?

I'm willing to provide a PR. How long the  timeout is set here better? 10s？

**Comment by alex-spataru** [comment]
> I'm willing to provide a PR. How long the timeout is set here better? 10s？

Thanks! I believe that is a good value, anything between 10-15s should suffice for most cases.
