### ISSUE TITLE
UnknownContentError in Update response

### ISSUE THREAD

**Issue by prabindh** [alex-spataru/QSimpleUpdater#6]
With Qt5.7 and Win10, QNetworkRequest(url()) returns UnknownContentError.  To ensure response is correctly received, need to set user-agent string before making the request. Would be good to expose an API for it, or use some default string (like Mozilla/*).

**Comment by alex-spataru** [comment]
I think that the best thing to do would be to expose an API that allows programmers to set an user-agent string before making a request. If no user-agent string is provided, QSimpleUpdater could fall-back to some default user-agent string. 

I'll take a look at this issue later this evening. Thanks for the report!

**Comment by prabindh** [comment]
Any update ?

**Comment by alex-spataru** [comment]
@prabindh Sorry for the late reply, I have added a simple API that allows you to set a custom user-agent string. By default, the user-agent string will be `<app-name>/<app-version> (Qt; QSimpleUpdater)`. Let me know if this works for you!

**Comment by prabindh** [comment]
That works, thanks!
