### ISSUE TITLE
Compile error with QT 5.5 and Visual Studio 2013

### ISSUE THREAD

**Issue by stevemenke** [alex-spataru/QSimpleUpdater#7]
I get the following error building QSimpleUpdater:
`        cl -c -nologo -Zc:wchar_t -FS -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -EHsc /Fddebug\QSimpleUpdater.pdb -DUNICODE -DWIN32 -DQSU_SHARED -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_OPENGL_ES_2 -DQT_OPENGL_ES_2_ANGLE -I. -Iinclude -I..\..\..\..\Qt\5.5\Src\qtbase\include -I..\..\..\..\Qt\5.5\Src\qtbase\include\QtWidgets -I..\..\..\..\Qt\5.5\Src\qtbase\include\QtGui -I..\..\..\..\Qt\5.5\Src\qtbase\include\QtANGLE -I..\..\..\..\Qt\5.5\Src\qtbase\include\QtNetwork -I..\..\..\..\Qt\5.5\Src\qtbase\include\QtCore -Idebug -I. -I..\..\..\..\qt\5.5\src\qtbase\mkspecs\win32-msvc2013 -Fodebug\ @C:\Users\STEVEM~1\AppData\Local\Temp\nmCFBB.tmp
Downloader.cpp
src\Downloader.cpp(116) : error C2027: use of undefined type 'QDateTime'
        c:\qt\5.5\src\qtbase\include\qtcore\../../src/corelib/kernel/qmetatype.h(1873) : see declaration of 'QDateTime'
src\Downloader.cpp(116) : error C2228: left of '.toTime_t' must have class/struct/union
        type is 'unknown-type'
src\Downloader.cpp(116) : error C3861: 'currentDateTime': identifier not found
src\Downloader.cpp(340) : error C2027: use of undefined type 'QDateTime'
        c:\qt\5.5\src\qtbase\include\qtcore\../../src/corelib/kernel/qmetatype.h(1873) : see declaration of 'QDateTime'
src\Downloader.cpp(340) : error C2228: left of '.toTime_t' must have class/struct/union
        type is 'unknown-type'
src\Downloader.cpp(340) : error C3861: 'currentDateTime': identifier not found
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.`

I was able to fix it by adding `#include <QDateTime>` to Downloader.cpp. I would have created a pull request by I did not see a way to contribute to the project.

**Comment by alex-spataru** [comment]
Thanks for the report!
