### ISSUE TITLE
Issue downloading update on Windows

### ISSUE THREAD

**Issue by aziesemer** [alex-spataru/QSimpleUpdater#8]
The test for download finished should be:
    if (received >= total && total > 0 && this->m_reply->isFinished()) 
and not just:
    if (received >= total && total > 0) 
in the void Downloader::saveFile (qint64 received, qint64 total) function.

In my case I am not sure if there was a redirection or something, but the file was not downloading because of that on Windows. On Mac OS it was fine.

**Comment by alex-spataru** [comment]
Thanks for the report! I will update the code in a moment.

**Comment by aziesemer** [comment]
Maybe this is the right way to fix it: 
https://github.com/gilmanov-ildar/QSimpleUpdater/commit/d017a4299d991af9d002e763c6b9d02b72385538
