### ISSUE TITLE
How to update some modules only?

### ISSUE THREAD

**Issue by tonyho** [alex-spataru/QSimpleUpdater#9]
This program is wonderful, and easy to use. But what if I want to update some modules of my installed program?  It seems the QSimpleUpdater is just download and run the downloaded file?  

And I want to download and replace the local files, can you write a guide or give some help? Thanks.

**Comment by alex-spataru** [comment]
QSimpleUpdater supports the functionality that you want, you can use the [signals](https://github.com/alex-spataru/QSimpleUpdater/blob/master/include/QSimpleUpdater.h#L70) of the library to implement your own functions to 'install' the updates. I will begin writing a wiki later this week.
